chore: aligned service versions with integration
mendersoftware/mender-helm pull request #172
Opened 2023-07-21 21:02 UTC by mzedel

to align with
https://github.com/mendersoftware/integration/blob/master/docker-compose.yml#L60
https://github.com/mendersoftware/integration/blob/master/docker-compose.yml#L270

2023-07-21 21:05 UTC, oldgiova commented
LGTM, let's also ask @tranchitella because he's the release manager

2023-07-21 21:06 UTC, oldgiova approved these changes

2023-07-22 07:12 UTC, tranchitella commented
@mzedel and @oldgiova, we are running 4.4.x in production now.
I prefer to release Mender 3.6 (LTS) with this version and leave the upgrade to 5.0.x in the next release cycle.
What do you think?

2023-07-22 07:13 UTC, tranchitella requested changes

2023-07-22 07:13 UTC, tranchitella commented on mender/values.yaml
> +    tag: v2.8
This is okay.

2023-07-22 07:13 UTC, tranchitella commented on mender/values.yaml
> +    tag: "5.0"
This one I don't want to include in the release.

2023-07-24 07:21 UTC, tranchitella approved these changes

2023-07-24 07:21 UTC, merged

2023-07-24 07:21 UTC, tranchitella commented
Thanks @mzedel, I merged.