use k8s service account to access s3 bucket
mendersoftware/mender-helm pull request #36
Opened 2021-06-17 07:21 UTC by ffoysal

Signed-off-by: Foysal Iqbal <foysal.iqbal.fb@gmail.com>

Once the K8s cluster in AWS infrastructure use can use service account to access aws resources. detail explanation is in https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/ 

In order to use K8s service account according to this need to provide `serviceAccountName` in the pod spec. User does not need to provide `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` if they want to use k8s service account. If they dont want to use service account the default behavior in chart remains as before.

Signed-off-by: Foysal Iqbal <foysal.iqbal.fb@gmail.com>

2021-07-03 03:51 UTC, tranchitella requested changes
See my comments to make the naming of the options consistent.
Please update README.md as well documenting the new options.

2021-07-03 03:51 UTC, tranchitella commented on mender/values.yaml
> +    useServiceAccount: "false"
To keep the configuration option consistent with the other ones, I'd rather suggest:
```suggestion
    AWS_SERVICE_ACCOUNT_NAME: ""
```

2021-07-03 03:51 UTC, tranchitella commented on mender/templates/secret-s3-artifacts.yaml
> +{{- end }}
```suggestion
{{- if not .Values.global.s3.AWS_SERVICE_ACCOUNT_NAME }}
  AWS_AUTH_KEY: {{ .Values.global.s3.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_AUTH_SECRET: {{ .Values.global.s3.AWS_SECRET_ACCESS_KEY | b64enc }}
{{- end }}
```

Pay attention to the missing new lline at the end of the file

2021-07-03 03:51 UTC, tranchitella commented on mender/templates/deployments-deploy.yaml
> +{{- end }}
```suggestion
{{- if .Values.global.s3.AWS_SERVICE_ACCOUNT_NAME }}
      serviceAccountName: {{ .Values.global.s3.AWS_SERVICE_ACCOUNT_NAME }}
{{- end }}
```

2021-07-03 05:35 UTC, ffoysal commented
@tranchitella Thank you very much for the feedback. updated accordingly.

2021-07-04 04:28 UTC, tranchitella reviewed
@ffoysal thanks, it looks good. Our CI/CD doesn't recognize the Co-authored-by tag, though. I kindly ask you to squash your commits into one, using both the Signed-off-by tag and a Changelog, e.g.

Changelog: Use k8s service account to access s3 bucket

2021-07-04 21:22 UTC, ffoysal commented
@tranchitella this branch got dirty, so created a new PR https://github.com/mendersoftware/mender-helm/pull/39
hope that will not have any issue.

2021-07-05 03:21 UTC, tranchitella commented
Superseded by https://github.com/mendersoftware/mender-helm/pull/39

2021-07-05 03:21 UTC, closed without merging